<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>asynchronous-task</title>
    <style>
    body {
        background-color: tan;
        margin: 0;
        font-family: Verdana, sans-serif;
    }

    .title {
        color: red;
        text-align: center;
        font-weight:700;
    }

    .task{
        width: 50%;
        padding: 15px 25px;
        color: navy;
        background-color: #e2e2e2;
        margin: 35px auto;
    }

    .code-ex {
        width: 50%;
        font-family: sans-serif;
        background-color: #bebebe;
        font-size: large;
        padding-left: 15px;
        margin: 0 auto;
    }

    p {
        width: 80%;
        margin: 0 auto;
    }
    </style>
</head>
<body>

    <h2 class="title">Асинхронный код, контрольное задание</h2>

    <h4 class="task">В этом задании необходимо реализовать функцию parallel, которая выполняет асинхронные операции параллельно.<br>
                    Функция parallel принимает два аргумента: массив операций и результирующий callback.
    </h4>

    <p class="code-ex">
        <code>
            var parallel = require('./index.js);<br>
            <br>
            parallel (<br>
                [<br>
                    function (next) { /* асинхронная операция 1 */ },<br>
                    function (next) { /* асинхронная операция 2 */ },<br>
                    // ...<br>
                ],<br>
                function(err, result) {<br>
                    // обработка результата выполнения операций<br>
                }<br>
            )<br>
            <br>
        </code>
    </p>

    <h3>Условия</h3>

    <p>Операции
        Каждая операция – это синхронная или асинхронная функция. На вход ей приходит callback-функция 
        next. По завершению работы операция вызывает функцию next либо с результатом выполнения, либо 
        с ошибкой.<br>
        Если операция успешно завершилась, то вызывается callback-функция с первым аргументом null, а
         вторым – результатом выполнения:
        </p>
    <p>

    <p class="code-ex">
        <code>
            function (next) {<br>
                setTimeout(function () {<br>
                    next(null, 'data');<br>
                }, 1000);<br>
            }<br>
            <br>
        </code>
    </p>

    <p>Если операция завершается с ошибкой, то callback-функция вызывается с единственным аргументом – 
        возникшей ошибкой:
    </p>
    
    <p class="code-ex">
        <code>
            function (next) {<br>
                setTimeout(function () {<br>
                    next(new Error('Что-то пошло не так'));<br>
                }, 1000);<br>
            }<br>
            <br>
        </code>
    </p>

    <h3>Результирующий callback</h3>

    <p>Результирующий callback (второй параметр функции parallel) вызывается по окончанию выполнения 
        всех операций или при возникновения ошибки в одной из них.<br>
        Если все операции завершились успешно, в callback передаётся первым аргументом null, а 
        вторым – массив с результатами выполнения операций. Порядок данных должен соответствовать 
        порядку операций в массиве, а не их вызову.<br>
        Если не переданы операции (передан пустой массив), то результатом выполнения должен быть пустой 
        массив.<br>
        Если хотя бы одна из операций закончилась ошибкой, то callback-функция вызывается с произошедшей 
        ошибкой. Если несколько операцией завершились ошибкой, то callback будет вызван с первой из них.<br>
        Важно. Callback вызывается ровно один раз: либо с первой пойманной ошибкой, либо с результатами 
        выполнения операций.
    </p>

    <h3>Ограничения</h3>

    <p>1.Гарантируется корректность вызова функции parallel и передача операций в правильном формате.<br>
       2.Гарантируется, что функция next всегда вызывается в операциях.
    </p>

    <h3>Пояснения</h3>

    <p>В данном задании используется термин callback. При этом подходе в асинхронную функцию передается 
        другая функция, которую исходная должна вызвать по завершению. Это способ асинхронной функции 
        сообщить о своем завершении.
    </p>

    <p class="code-ex">
        <code>
            setTimeout(function callback() {<br>
                // Функция setTimeout вызовет нашу callback-функцию, когда завершит отсчет 1000 ms
            }, 1000);
            <br>
        </code>
    </p>

    <p>По условию задачи мы имеем дело с двумя callback-функциями:<br>
        1. Функция next — передается в операцию, которая по своему завершению должна вызвать функцию next.<br>
        2. Вторая функция используется внутри операции, чтобы узнать о завершении работы setTimeout.
    </p>

    <p class="code-ex">
        <code>
            function operation(next) {<br>
                setTimeout(function callback() {<br>
                    // Данная функция вызывается по завершению setTimeout<br>
                    // Мы вызываем функцию next, чтобы сообщить о завершении работы функции operation<br>
                    next(null, 'data');<br>
                }, 1000);<br>
              }<br>
            <br>
        </code>
    </p>

    <p>В данном примере функция setTimeout сама вызывает callback, а для функции operation 
        callback-функцию (next) мы вызываем вручную. Использование функции operation практически 
        не отличается от использования функции setTimeout:
    </p>

    <p class="code-ex">
        <code>
            // Вызываем функцию operation, в которую передаем callback<br>
            operation(function callback(err, data) {<br>
                // Данная функция будет вызвана по завершению асинхронной функции operation<br>
            })<br>
            <br>
        </code>
    </p>

    <h3>Подсказка</h3>

    <p>Сохранение порядка можно сделать через замыкания, для каждой операции создавая функцию next</p>




</body>

</html>